# =============================================================================
# OPENSPEC COMPLETIONS (generated by OpenSpec)
# =============================================================================
# OPENSPEC:START
fpath=("$HOME/.oh-my-zsh/custom/completions" $fpath)
autoload -Uz compinit
compinit
# OPENSPEC:END

# =============================================================================
# KIRO CLI PRE-HOOK (must be near top)
# =============================================================================
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"

# =============================================================================
# AGENT MODE DETECTION
# =============================================================================
# Detect AI agents (CI, non-interactive shells) and enable minimal mode
if [[ -n "$npm_config_yes" ]] || [[ -n "$CI" ]] || [[ "$-" != *i* ]]; then
  export AGENT_MODE=true
else
  export AGENT_MODE=false
fi

if [[ "$AGENT_MODE" == "true" ]]; then
  POWERLEVEL9K_INSTANT_PROMPT=quiet
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
  export DEBIAN_FRONTEND=noninteractive
  export NONINTERACTIVE=1
fi

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# =============================================================================
# POWERLEVEL10K INSTANT PROMPT
# =============================================================================
if [[ "$AGENT_MODE" != "true" ]] && [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# =============================================================================
# OH MY ZSH
# =============================================================================
export ZSH="$HOME/.oh-my-zsh"

# Theme (Powerlevel10k overrides this when active)
if [[ "$AGENT_MODE" == "true" ]]; then
  ZSH_THEME=""
else
  ZSH_THEME="robbyrussell"
fi

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)

source $ZSH/oh-my-zsh.sh

# =============================================================================
# POWERLEVEL10K THEME
# =============================================================================
if [[ "$AGENT_MODE" == "true" ]]; then
  PROMPT='%n@%m:%~%# '
  RPROMPT=''
  unsetopt CORRECT
  unsetopt CORRECT_ALL
  setopt NO_BEEP
  setopt NO_HIST_BEEP
  setopt NO_LIST_BEEP
  
  # Agent-friendly aliases to avoid interactive prompts
  alias rm='rm -f'
  alias cp='cp -f'
  alias mv='mv -f'
  alias npm='npm --no-fund --no-audit'
  alias yarn='yarn --non-interactive'
  alias pip='pip --quiet'
  alias git='git -c advice.detachedHead=false'
else
  # Load Powerlevel10k for interactive use (Homebrew path for Apple Silicon)
  [[ -f /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme ]] && source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
fi

# =============================================================================
# PATH CONFIGURATION
# =============================================================================
export PATH="$HOME/.local/bin:$PATH"                    # uv, pipx
export PATH="$HOME/.toolbox/bin:$PATH"                  # Amazon toolbox
export PATH="$HOME/.bun/bin:$PATH"                      # Bun runtime
export PATH="$HOME/.opencode/bin:$PATH"                 # OpenCode CLI
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"  # Antigravity
export PATH="$HOME/.codeium/windsurf/bin:$PATH"         # Windsurf (optional)
export PATH="$HOME/.console-ninja/.bin:$PATH"           # Console Ninja

# MCP servers paths
[[ -d "$HOME/.config/smithy-mcp/mcp-servers" ]] && export PATH="$HOME/.config/smithy-mcp/mcp-servers:$PATH"
[[ -d "$HOME/.aim/mcp-servers" ]] && export PATH="$HOME/.aim/mcp-servers:$PATH"

# =============================================================================
# AWS
# =============================================================================
export AWS_REGION="eu-west-1"
export AWS_PAGER=""

# AWS SSO shortcuts — login + set profile in one command
awslogin() {
  local profile="$1"
  if [[ -z "$profile" ]]; then
    echo "Usage: awslogin <profile>"
    return 1
  fi
  local session=$(aws configure get sso_session --profile "$profile" 2>/dev/null)
  if [[ -z "$session" ]]; then
    echo "Profile '$profile' not found or has no sso_session"
    return 1
  fi
  if aws sso login --sso-session "$session"; then
    export AWS_PROFILE="$profile"
    echo "Logged in and AWS_PROFILE set to: $profile"
  else
    echo "Login failed for session '$session'"
    return 1
  fi
}

# Just switch profile (no login, assumes already authenticated)
awsuse() {
  local profile="$1"
  if [[ -z "$profile" ]]; then
    echo "Usage: awsuse <profile>"
    return 1
  fi
  export AWS_PROFILE="$profile"
  echo "AWS_PROFILE set to: $profile"
  aws sts get-caller-identity 2>/dev/null || echo "Session expired — run: awslogin $profile"
}

# Per-org shortcuts: login (al*) and use (au*)
alias alcred="awslogin crediteame"
alias aucred="awsuse crediteame"
alias alinv="awslogin investtup"
alias auinv="awsuse investtup"
alias alcrit="awslogin criteria"
alias aucrit="awsuse criteria"
# alias allight="awslogin lighthouse"
# alias aulight="awsuse lighthouse"

# Export SSO credentials to [default] in ~/.aws/credentials
# so any process on the machine (even spawned terminals) can use them.
# Auto-triggers awslogin if the session is expired.
awsexport() {
  local profile="${1:-$AWS_PROFILE}"
  if [[ -z "$profile" ]]; then
    echo "Usage: awsexport <profile>  (or set AWS_PROFILE first)"
    return 1
  fi
  # Check if credentials are available (discard output, just test exit code)
  if ! aws configure export-credentials --profile "$profile" --format env-no-export >/dev/null 2>&1; then
    echo "Session expired for '$profile', logging in..."
    awslogin "$profile" || return 1
  fi
  # Capture credentials (stderr discarded so it doesn't corrupt output)
  local creds
  creds=$(aws configure export-credentials --profile "$profile" --format env-no-export 2>/dev/null)
  if [[ $? -ne 0 ]]; then
    echo "Failed to get credentials for '$profile' even after login."
    return 1
  fi
  local key secret token
  key=$(echo "$creds" | grep AWS_ACCESS_KEY_ID | cut -d= -f2)
  secret=$(echo "$creds" | grep AWS_SECRET_ACCESS_KEY | cut -d= -f2)
  token=$(echo "$creds" | grep AWS_SESSION_TOKEN | cut -d= -f2)
  aws configure set aws_access_key_id "$key" --profile default
  aws configure set aws_secret_access_key "$secret" --profile default
  aws configure set aws_session_token "$token" --profile default
  export AWS_PROFILE="$profile"
  echo "Default credentials set from profile '$profile' (AWS_PROFILE=$profile)"
  aws sts get-caller-identity --profile default 2>/dev/null
}

# Per-org shortcuts: export to default (ae*)
alias aecred="awsexport crediteame"
alias aeinv="awsexport investtup"
alias aecrit="awsexport criteria"

# Isengard — fetch temp credentials via ada and write to [default]
# so any process on the machine can use them (same pattern as awsexport for SSO)
isengardexport() {
  local account="$1"
  local role="${2:-Admin}"
  if [[ -z "$account" ]]; then
    echo "Usage: isengardexport <account-email> [role]"
    return 1
  fi
  echo "Fetching credentials for '$account' (role: $role)..."
  if ada credentials update --account "$account" --role "$role" --profile default --once; then
    export AWS_PROFILE="default"
    echo "Default credentials set from Isengard account '$account'"
    aws sts get-caller-identity --profile default 2>/dev/null
  else
    echo "Failed to get credentials for '$account'"
    return 1
  fi
}

# Per-account shortcuts: Isengard export to default (il*)
alias ilcc="isengardexport clopca+cc@amazon.es"
alias ilsandbox="isengardexport clopca+aisandbox@amazon.es"
alias ilkiro="isengardexport clopca+kiro@amazon.es"
alias ilnet="isengardexport clopca+ceca+net@amazon.es"

# =============================================================================
# DOCKER
# =============================================================================
export DOCKER_BUILDKIT=0
export DOCKER_DEFAULT_PLATFORM=linux/amd64
[[ -d "$HOME/.docker/completions" ]] && fpath=($HOME/.docker/completions $fpath)

# =============================================================================
# COMPLETIONS
# =============================================================================
autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit && compinit
[[ -f /opt/homebrew/bin/terraform ]] && complete -o nospace -C /opt/homebrew/bin/terraform terraform

# =============================================================================
# FNM (Fast Node Manager) - Preferred over NVM
# =============================================================================
if command -v fnm &> /dev/null; then
  eval "$(fnm env)"
fi

# =============================================================================
# NVM (Node Version Manager) - Alternative to FNM
# =============================================================================
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# =============================================================================
# BUN
# =============================================================================
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# =============================================================================
# VOLTA (Alternative Node version manager)
# =============================================================================
export VOLTA_HOME="$HOME/.volta"
[[ -d "$VOLTA_HOME/bin" ]] && export PATH="$VOLTA_HOME/bin:$PATH"

# =============================================================================
# DIRENV (Environment switcher for projects)
# =============================================================================
if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi

# =============================================================================
# 1PASSWORD CLI PLUGINS
# =============================================================================
[[ -f ~/.config/op/plugins.sh ]] && source ~/.config/op/plugins.sh

# =============================================================================
# CLAUDE / AI TOOLS
# =============================================================================
export CLAUDE_CODE_USE_BEDROCK=1
alias claude-code="export AWS_PROFILE=claudecode && export CLAUDE_CODE_USE_BEDROCK=1 && export ANTHROPIC_MODEL='global.anthropic.claude-sonnet-4-5-20250929-v1:0' && export DISABLE_TELEMETRY=1 && claude"

# =============================================================================
# OPENCODE CLI
# =============================================================================
alias oc="opencode"
alias ocr="opencode run"

# =============================================================================
# CURSOR / VS CODE
# =============================================================================
alias c="cursor"
alias code="cursor"

# =============================================================================
# KIRO CLI (if installed)
# =============================================================================
if command -v kiro-cli &> /dev/null; then
  KIRO_MODEL="claude-opus-4.5"
  alias kiromin='kiro-cli chat --agent kiro-main --model $KIRO_MODEL --trust-all-tools'
  
  salog() {
    local week="${1:-this}"
    kiro-cli chat --agent sa-logger --model $KIRO_MODEL --trust-all-tools "log my activities from $week week"
  }
  
  awsprice() {
    kiro-cli chat --agent aws-pricing-agent --model $KIRO_MODEL --trust-all-tools "$*"
  }
  
  awsknow() {
    kiro-cli chat --agent aws-knowledge-agent --model $KIRO_MODEL --trust-all-tools "$*"
  }
  
  mycal() {
    local when="${1:-today}"
    kiro-cli chat --agent outlook-agent --model $KIRO_MODEL --trust-all-tools "What meetings do I have $when?"
  }
  
  sentral() {
    kiro-cli chat --agent sentral-agent --model $KIRO_MODEL --trust-all-tools "Search for $*"
  }
fi

# =============================================================================
# OBSIDIAN
# =============================================================================
alias obsidian='open -a Obsidian && sleep 1 && open "obsidian://open?vault=clopca-obsidian-vault"'

# =============================================================================
# VS CODE / KIRO SHELL INTEGRATION
# =============================================================================
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  command -v kiro &> /dev/null && . "$(kiro --locate-shell-integration-path zsh)"
fi

# =============================================================================
# CUSTOM ALIASES
# =============================================================================
[[ -f ~/.aliases ]] && source ~/.aliases

# =============================================================================
# LOCAL CONFIGURATION (machine-specific, not in git)
# =============================================================================
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# =============================================================================
# WORK-SPECIFIC TOOLS (source if exists)
# =============================================================================
[[ -f "$HOME/dev/aws/oc-sa-toolkit/opencode-aliases.sh" ]] && source "$HOME/dev/aws/oc-sa-toolkit/opencode-aliases.sh"

# =============================================================================
# KIRO CLI POST-HOOK (must be at bottom)
# =============================================================================
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
